---
- name: Confirm which 'virt' stream is enabled
  ansible.builtin.shell:
    cmd: "dnf module list --enabled | grep virt | tr -s ' ' | cut -d  ' ' -f2"
  register: module_result

- name: Reset stream if required
  ansible.builtin.shell:
    cmd: 'dnf module reset virt:rhel -y'
  when: module_result.stdout.find('av') != -1 or module_result.stdout != ''

- name: Configure correct stream
  ansible.builtin.shell:
    cmd: 'dnf module enable virt:av -y'
  when: module_result.stdout.find('av') != -1 or module_result.stdout == ""

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - cephadm-ansible
      - cockpit-ovirt-dashboard